version: '3'

services:
  api:
    build:
      context: .
    container_name: jwtsample
    ports:
    - 8000:8080
    depends_on:
    - db
    environment:
      JAVA_ENV: dev
      DATABASE_URL: jdbc:mysql://db:3306/jwtsample
      DATABASE_USER: root
      DATABASE_PASSWORD: root

  db:
    image: mysql:latest
    container_name: jwtsample-db
    ports:
    - 3306:3306
    environment:
    - MYSQL_DATABASE=jwtsample
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_PASSWORD=root